name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: menezmethod/.github/.github/workflows/ci-go.yml@main
    with:
      go-version: "1.23"
      run-vet: true
      run-race: true